uc_data<-read.csv.sql("household_power_consumption.txt",sql="select * from file where (Date='1/2/2007' or Date='2/2/2007')", header=TRUE, sep=";")
uc_data$weekday<-NA
x<-paste(uc_data$Date, uc_data$Time)
uc_data$weekday<-strptime(x, "%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(uc_data$weekday, uc_data$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(uc_data$weekday, uc_data$Voltage, type="l", xlab="datetime", ylab="Voltage")
with(uc_data, plot(weekday, Sub_metering_1, col="black",type="l", xlab="", ylab="Energy sub metering"))
lines(uc_data$weekday, uc_data$Sub_metering_2, col="red", type="l")
lines(uc_data$weekday, uc_data$Sub_metering_3, col="blue", type="l" )
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"), cex=0.8)
plot(uc_data$weekday, uc_data$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, "plot4.png", width=480, height=480)
dev.off()
